services:
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "astro$17"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "bpanet"
    ports:
      - "5432:5432"
  app:
    image: "bpaapi"
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev && npm run dev"